version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "ras0q"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "ras0q"
  - package-ecosystem: docker
    directory: "/development"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "ras0q"
  - package-ecosystem: docker
    directory: "/development/test"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "ras0q"
