version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: knoq_app
    environment:
      TZ: Asia/Tokyo
      MARIADB_USERNAME: root
      MARIADB_PASSWORD: password
      MARIADB_HOSTNAME: mysql
      MARIADB_DATABASE: knoQ
      ORIGIN: http://localhost:6006
      SESSION_KEY: ${SESSION_KEY:-random32wordsXXXXXXXXXXXXXXXXXXX}
      TRAQ_CALENDARID: ${TRAQ_CALENDARID}
      CLIENT_ID: ${CLIENT_ID:-aYj6mwyLcpBIrxZZD8jkCzH3Gsdqc9DJqle2}
      WEBHOOK_ID: ${WEBHOOK_ID}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      CHANNEL_ID: ${CHANNEL_ID}
      DAILY_CHANNEL_ID: ${DAILY_CHANNEL_ID}
      ACTIVITY_CHANNEL_ID: ${ACTIVITY_CHANNEL_ID}
      TOKEN_KEY: ${TOKEN_KEY:-random32wordsXXXXXXXXXXXXXXXXXXX}
      KNOQ_VERSION: ${KNOQ_VERSION:-dev}
      DEVELOPMENT: true
      GORM_LOG_LEVEL: info
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      mysql:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./

  mysql:
    image: mariadb:10.6.4
    container_name: knoq_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: knoQ
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - "./_development/mariadb:/var/lib/mysql"
    expose:
      - "3306"
    healthcheck:
      test: mysql --user=root --password=password --execute "SHOW DATABASES;"
      interval: 1s
      timeout: 10s
      retries: 60

  adminer:
    image: adminer
    container_name: knoq_adminer
    ports:
      - "8000:8080"
    depends_on:
      mysql:
        condition: service_healthy
