name: CI

on:
  push:
    branches:
      - "**"
      - "!master"
    tags-ignore:
      - "**"

jobs:
  mod:
    name: go mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - run: go mod download

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOCACHE: "/tmp/go/cache"
    steps:
      - uses: actions/checkout@v2

      - name: Login GitHub Registry
        run: docker login docker.pkg.github.com -u traPtitech -p ${{ secrets.GITHUB_TOKEN }}
      - name: build traQ and DB environment
        run: docker-compose up -d

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - uses: actions/cache@v1
        with:
          path: /tmp/go/cache
          key: ${{ runner.os }}-go-build-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ github.ref }}-
            ${{ runner.os }}-go-build-
      - name: Run repository tests
        run: |
          go test ./repository