name: CI

on:
  push:
    branches:
      - "**"
      - "!master"
    tags-ignore:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true
      - run: go mod download
      - run: go build -v ./...

  test-unit:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true
      - run: go test -v $(go list ./... | grep -v "/infra/")

  test-repo:
    name: Repository Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: build traQ and DB environment
        run: docker compose up --build -d traQ-backend traQ-frontend mysql
        working-directory: ./development/test
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Run repository tests
        run: |
          go test -v ./infra...
